# fly.toml app configuration file generated for carbot-lingering-water-9015 on 2025-02-03T12:22:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'carbot-lingering-water-9015'
primary_region = 'ewr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
